// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HTTPPostUpdateOrder is an autogenerated mock type for the HTTPPostUpdateOrder type
type HTTPPostUpdateOrder struct {
	mock.Mock
}

// CallUpdateOrdersService provides a mock function with given fields: _a0, _a1
func (_m *HTTPPostUpdateOrder) CallUpdateOrdersService(_a0 string, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewHTTPPostUpdateOrder interface {
	mock.TestingT
	Cleanup(func())
}

// NewHTTPPostUpdateOrder creates a new instance of HTTPPostUpdateOrder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHTTPPostUpdateOrder(t mockConstructorTestingTNewHTTPPostUpdateOrder) *HTTPPostUpdateOrder {
	mock := &HTTPPostUpdateOrder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
